### ISSUE TITLE
let and if then else expressions

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon.formatter#104]
The new let and if then else expressions allow doing some nesting like this :
```Ceylon
function buildParents(String entry) 
    => let(parents = entry.split('/'.equals).filter(not(String.empty)).exceptLast)
            if (exists firstParent = parents.first)
            then
                if (nonempty restOfParents = parents.rest.sequence())
                then restOfParents.scan(firstParent + "/")(
                    (path, nextParent) => "".join { path, nextParent + "/"})
                else { firstParent + "/"}
            else {};
```

However the Ceylon formatter formats it like that :
```Ceylon
function buildParents(String entry)
        => let (parents = entry.split('/'.equals).filter(not(String.empty)).exceptLast)
    if (exists firstParent = parents.first)
            then
    if (nonempty restOfParents = parents.rest.sequence())
            then restOfParents.scan(firstParent + "/")(
        (path, nextParent) => "".join { path, nextParent + "/" })
            else { firstParent + "/" }
            else {};
```

**Comment by lucaswerkmeister** [comment]
Two things here:

1. [ ] Indentation of `=>` should stack – can be emulated by separately creating the context
2. [ ] `if` should have a proper indentation after it, and `then` and `else` shouldn’t have any indentation before them

**Comment by lucaswerkmeister** [comment]
> if should have a proper indentation after it

Hm… which one is better?
```ceylon
if (c)
    then x
    else y
```
```ceylon
if (c)
then x
else y
```

Perhaps the issue is rather that `then` and `else` should introduce indentation, not `if`.

**Comment by lucaswerkmeister** [comment]
If expression part is done. `=>` is a complicated issue which I keep forgetting I’ve already tried to solve; I’ll create a new issue for that.

**Comment by luolong** [comment]
I prefer this (its more regular):
```ceylon
if (c)
then x
else y
```

**Comment by lucaswerkmeister** [comment]
I agree, and that’s what we have now.
