### ISSUE TITLE
Keep blank lines introduced by "Organize Imports"

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon.formatter#119]
"Organize Imports" groups imports by packages "roots", like this:

```
import ceylon.foo { ... }
<blank line>
import java.xyz { ... }
<blank line>
import org.xyz { ... }
import org.abc { ... } // no blank line here
```

It would be nice if the formatter kept those blank lines.

Also, I think it would be cool to force a blank line between the imports section and the first declaration (which seems to be a convention, for example in the SDK).

**Comment by lucaswerkmeister** [comment]
Should be done, both parts. Reopen if not :)
