### ISSUE TITLE
Switch to using a plugin file instead of scripts

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon.formatter#120]
See `ceylon-compiler/bin` for examples.
We can then copy it to `ceylon-dist/dist/bin` during the build so it's available by default.

**Comment by lucaswerkmeister** [comment]
Hm, first time I’m seeing those files – I’d have spoken up against the `; comment` syntax if I’d known earlier :/

So what do I do? Include a `CeylonFormatTool` class in `ceylon.formatter` and point to it with the plugin file?

**Comment by quintesse** [comment]
They are property files, I wasn't going to come up with a different format for the fun of it ;)

It doesn't have a `Tool` yet? Ok, I didn't know that. It would be the nicest solution though as it would integrate best into the tool chain. But if it's too difficult or too much work we can add the scripts themselves to the distribution as well I guess.

**Comment by lucaswerkmeister** [comment]
Well, AFAIK properties files are usually commented with `#`… but it’s not a standardized format.

And no, there’s no `Tool` yet, but I’ll be very happy to get rid of the ugly batch script :)

**Comment by lucaswerkmeister** [comment]
I’ll probably have to generate the tool to get the options right…

**Comment by lucaswerkmeister** [comment]
> I’ll probably have to generate the tool to get the options right…

Nope, I cheesed it with `Rest` :D

**Comment by quintesse** [comment]
Great! Now we only need to integrate this with the distribution (your https://github.com/ceylon/ceylon-dist/issues/43 issue)
