### ISSUE TITLE
if/else each on one line not supported

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon.formatter#130]
```ceylon
if (true) { print(1); }
else { print(2); }
```
The formatter turns this into
```
if (true) { print(1); } else { print(2); }
```
because an `else` normally goes on the same line as the preceding `}`, under the assumption that this `}` is already on its own line. Single-line `if`s violate that assumption.

Which solution would be preferred here?

- Don’t allow single-line `if`s with an `else`: turn this into
  ```ceylon
  if (true) {
      print(1);
  } else {
      print(2);
  }
  ```
  Tricky because we need to propagate this information into `visitBlock`.
- Detect the “single-line if” case at the `else`, and preserve the code unchanged.
  Also tricky because we need to propagate this information from `visitIfClause` to `visitElseClause`.

Thoughts?

**Comment by lucaswerkmeister** [comment]
If we decide to not allow single-line `if`s with an `else` (first solution), then the implementation would probably be a `Category` of `Block`s that are not allowed to be single-line (`FormattingVisitor` member), which `visitIf` adds blocks to and `visitBlock` consults. And in that case, I think I’d also like to add method blocks (and, if necessary, class/interface bodies) to that category as well.

**Comment by quintesse** [comment]
Personally I'm a proponent of the first solution. I *never* write single line ifs in Java for example, I always use blocks even for the tiniest of statements, I find the visual regularity more readable myself and prefer it over making the code shorter.
But I admit it's completely personal, I can perfectly understand people seeing things differently.

**Comment by lucaswerkmeister** [comment]
Well, those people still have to live with the fact that we didn’t make braces optional in Ceylon ;)

I think I prefer the first solution as well. I wrote the original code in the issue, but still, it looks weird to me now.

**Comment by gavinking** [comment]
@lucaswerkmeister I think whatever you do, it should be consistent with how you handle `switch` statements and `try` statements with `catch` clauses.

**Comment by lucaswerkmeister** [comment]
Well, currently, this is allowed:
```ceylon
try { print("hi"); } catch (Exception e) { e.printStackTrace(); } finally { print("done"); }
```
So I’d say those are some more candidates for blocks that aren’t allowed to have a single-line form.

It might actually make more sense to turn this around and say that only these kinds of blocks *are* allowed to be single-line (if they contain at most one statement):

- `if` with no `else`
- `case`
- `dynamic`, probably
- setters? not sure

Anything else? I looked for `Block` in the spec, and these are the only productions where single-line blocks make sense IMO. (Some constructs, like functions and getters, should instead use `=>` in these cases; others should never me single-line IMO.)
