### ISSUE TITLE
Documenting the formatting options

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon.formatter#91]
I'm not really sure that the documentation on the options being in the [herd API doc](https://modules.ceylon-lang.org/repo/1/ceylon/formatter/1.1.0/module-doc/api/options/FormattingOptions.type.html) is sufficiently accessible for people needing that doc.

So it would be nice if there was a way for the formatter to tell you what options it supported. Like running "ceylon format --optionhelp" would print detailed doc about the formatting options.

**Comment by lucaswerkmeister** [comment]
Closing this issue for now, if anyone’s unhappy with the current output please open a new issue.
